class Create
    
    def self.create_customer_hash(id_default_group = nil,
        id_lang = nil,
        newsletter_date_add = nil,
        ip_registration_newsletter = nil,
        last_passwd_gen = nil,
        secure_key = nil,
        deleted = nil,
        passwd = nil,
        lastname = nil, 
        firstname = nil,
        email = nil,
        id_gender = nil,
        birthday = nil,
        newsletter = nil,
        optin = nil ,
        website = nil,
        company = nil,
        siret = nil,
        ape = nil,
        outstanding_allow_amount = nil, 
        show_public_prices = nil,
        id_risk = nil,
        max_payment_days = nil,
        active = nil, 
        note = nil,   
        is_guest = nil,   
        id_shop = nil,
        id_shop_group = nil,
        date_add = nil,
        date_upd = nil,
        reset_password_token = nil,
        reset_password_validity = nil,
        id_group = nil)
            return Hash[
                :id_default_group => id_default_group,                                     
                :id_lang => id_lang ,                                     
                :newsletter_date_add => newsletter_date_add,                 
                :ip_registration_newsletter => ip_registration_newsletter,                                    
                :last_passwd_gen => last_passwd_gen,                 
                :secure_key => secure_key,    
                :deleted => deleted,                                     
                :passwd => passwd,                         
                :lastname => lastname,                            
                :firstname => firstname,                              
                :email => email,              
                :id_gender => id_gender,                                     
                :birthday => birthday,                          
                :newsletter => newsletter,                                     
                :optin => optin,                                     
                :website => website,                                    
                :company => company,                                    
                :siret => siret,                                    
                :ape => ape,                                    
                :outstanding_allow_amount => outstanding_allow_amount,                            
                :show_public_prices => show_public_prices,                                     
                :id_risk => id_risk,                                     
                :max_payment_days => max_payment_days,                                     
                :active => active,                                     
                :note => note,                                    
                :is_guest => is_guest,                                     
                :id_shop => id_shop,                                     
                :id_shop_group => id_shop_group,                                     
                :date_add => date_add,                 
                :date_upd => date_upd,                 
                :reset_password_token => reset_password_token,                                    
                :reset_password_validity => reset_password_validity,                 
                :id_group => id_group ]
               
    end

end

h1 = Create.create_customer_hash(3,1,"0000-00-00 00:00:00","","2022-07-07 04:59:11","09dbbc486ceeb311e0d7814915f947fc",0,"prestashop","Morawski","Kacper","kacper.morawski2@wp.pl",1,"0000-00-00",0,1,"","","","","0.000000",0,0,0,0,"",0,1,1,"2022-07-07 10:59:11","2022-07-07 10:59:11","","0000-00-00 00:00:00",3)
